version: 2
jobs:
  build:
    working_directory: /usr/src/app
    docker:
      - image: banian/node
    steps:
      # Checkout repository
      - checkout

      # install node
      - run:
          name: Install node@11.10.1
          command: |
           ./.circleci/load-nvm.sh
            nvm install v11.10.1
            nvm alias default v11.10.1
      
      # will print node: '11.10.1'
      - run: |
          ./load-nvm.sh
          npm version

      # Restore cache
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: NODE_ENV=dev yarn

      # Keep cache
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      # build
      - run: yarn build

      # Test
      - run: yarn test
      
      # Release 
      - run:
          name: release
          command: npm run semantic-release || true
          secrets: [ npm_token, gh_token ]